
{{ config(
    materialized    = 'semantic_view',
    meta={
        'semantic_view': 'true'
    }
) }}

TABLES (
  PROJECT_INDICATION_FLAT   AS {{ ref('vw_project_indication_flat') }}
    WITH SYNONYMS = ('PROJECT, ASSET and INDICATION information')
)

DIMENSIONS (
    PROJECT_INDICATION_FLAT.PROJECT_CODE AS PROJECT_CODE,
	PROJECT_INDICATION_FLAT.PROJECT_CATEGORY AS PROJECT_CATEGORY,
	PROJECT_INDICATION_FLAT.PROJECT_ORGANIZATION AS PROJECT_ORGANIZATION,
	PROJECT_INDICATION_FLAT.PROJECT_NAME AS PROJECT_NAME,
	PROJECT_INDICATION_FLAT.PROJECT_DESCRIPTION AS PROJECT_DESCRIPTION,
	PROJECT_INDICATION_FLAT.PROJECT_STATUS AS PROJECT_STATUS,
	PROJECT_INDICATION_FLAT.PROJECT_PHASE AS PROJECT_PHASE,
	PROJECT_INDICATION_FLAT.PROJECT_PRIORITY AS PROJECT_PRIORITY,
	PROJECT_INDICATION_FLAT.PROJECT_INNOVATION_STATUS AS PROJECT_INNOVATION_STATUS,
	PROJECT_INDICATION_FLAT.PROJECT_RESEARCH_DEVELOPMENT_LINK AS PROJECT_RESEARCH_DEVELOPMENT_LINK,
	PROJECT_INDICATION_FLAT.PROJECT_SANOFI_THERAPEUTIC_AREA AS PROJECT_SANOFI_THERAPEUTIC_AREA,
	PROJECT_INDICATION_FLAT.ASSET_INN AS ASSET_INN,
	PROJECT_INDICATION_FLAT.ASSET_BRAND_NAME AS ASSET_BRAND_NAME,
	PROJECT_INDICATION_FLAT.ASSET_MECHANISM_OF_ACTION AS ASSET_MECHANISM_OF_ACTION,
	PROJECT_INDICATION_FLAT.ASSET_ACTIVE_SUBSTANCE_TYPE AS ASSET_ACTIVE_SUBSTANCE_TYPE,
	PROJECT_INDICATION_FLAT.ASSET_ACTIVE_SUBSTANCE_SUBTYPE AS ASSET_ACTIVE_SUBSTANCE_SUBTYPE,
	PROJECT_INDICATION_FLAT.ASSET_ORIGIN_OF_ACTIVE_SUBSTANCE AS ASSET_ORIGIN_OF_ACTIVE_SUBSTANCE,
	PROJECT_INDICATION_FLAT.INDICATION_UNIQUE_CODE AS INDICATION_UNIQUE_CODE,
	PROJECT_INDICATION_FLAT.INDICATION_LEAD_FLAG AS INDICATION_LEAD_FLAG,
	PROJECT_INDICATION_FLAT.INDICATION_LONGNAME AS INDICATION_LONGNAME,
	PROJECT_INDICATION_FLAT.INDICATION_SHORTNAME AS INDICATION_SHORTNAME,
	PROJECT_INDICATION_FLAT.INDICATION_PHASE AS INDICATION_PHASE,
	PROJECT_INDICATION_FLAT.INDICATION_CODE_MEDDRA AS INDICATION_CODE_MEDDRA,
	PROJECT_INDICATION_FLAT.INDICATION_NAME_MEDDRA AS INDICATION_NAME_MEDDRA,
	PROJECT_INDICATION_FLAT.INDICATION_STATUS AS INDICATION_STATUS,
	PROJECT_INDICATION_FLAT.INDICATION_SANOFI_THERAPEUTIC_AREA AS INDICATION_SANOFI_THERAPEUTIC_AREA,
	PROJECT_INDICATION_FLAT.INDICATION_SANOFI_SUB_THERAPEUTIC_AREA_FRANCHISE AS INDICATION_SANOFI_SUB_THERAPEUTIC_AREA_FRANCHISE,
	PROJECT_INDICATION_FLAT.INDICATION_PTRS AS INDICATION_PTRS
)

COMMENT = 'This is a flattened view showing PROJECT, ASSET, and INDICATION information sourced from the R&D MDM and RDPM. The only elements sourced from RDPM are Project Priority, Project Innovation Status, Lead Indication Flag, and PTRS. Everything else is sourced from the MDM data. \n\nIt is filtered for Pipeline projects with a status of Ongoing or Completed and project phases that fall in the pipeline development phases of ''M0-M1'',''M1-M2'',''M0-M2'',''Preclinical'',''Phase 1'',''Phase 2'',''Phase 2A'',''Phase 2B'',''Phase 3'',''Regulatory submission'', and ''LCM''.'